### ISSUE TITLE
Member class ako template argument

### ISSUE THREAD

**Issue by nandra** [logimic/RdsGatewayRepM3#11]
Ahoj, preparabl som troska BaseCommand class aby pre deserializaciu si ulozil typ interne podla definovanej struktury.
Neviem ani za svet presvedcit kompiler aby mi zozral takuto deklaraciu:
```
struct none { struct value_type {}; };

   class GetVersionCmd : public BaseCommand<none, GetVersionCmd::data_t> {
    public:
      GetVersionCmd() 
      : BaseCommand(COMMANDS_TYPE::CMD_GET_VERSION) {}
      
      struct data_t {
        UINT8 fw_version_minor;
        UINT8 fw_version_major;
        UINT8 fw_pre_release_nr;
        UINT8 hw_variant;
      };
  };
```

pise to ze: ```error: incomplete type ‘lgmc::GetVersionCmd’ used in nested name specifier```, skusal som to redtym definovat typedefom atd ale nejako to tiez nefunguje. Nemas nahodou napad ako toto poriesit? Vdaka.

**Comment by fmikulu** [comment]
Nevim, to bych si musel vyzkouset aby mi to tu chybu hlasilo a pohrat si s tim, pokud to mas trebars na nejake branch.
Nicmene prijde mi, ze si zbytecne komplikujes zivot s templates a vnorenymi strukturami.

Ja bych implementoval data type z RepM3 jako tridy  s metodami serialize() deserialize() (pripadne virtual a oddedene)
CMD tridy by byly odvozene od BaseCmd s pure virtual serializeCmd() = 0, deserializeCmd() - at se ty nazvy nepletou. Data typy by pak mely jako class membery Odvozene CMD tridy pak v implementaci serialCmd() deserialCmd() jen zavolaji serial() deserial() virtual metody asociovanych typu. Nic sloziteho.

Nektere RepM3 class typy  pak budou mit jeste encode(), parse() do JSON, jak popisuju v #10  protoze je potrebuju poslat pres API.

Asi behem zitra/pozitri budu delat neco podobneho pro IQRF, tak ti pak muzu poslat pro inspiraci. 

```cpp
class Version {
private:
 int major,
 int minor,

public:
  // v pripade version serialize neni treba
  void serialize(vector &) const {
    vector.push_back (major)
  }

  void deserialize(const vector &) {
    major = vector[0];
    //...
  }
  rapidjson::value *encode() const {
    //...
  }
 void  decode(const rapidjson::value*) {
    //...
  }
};

//slozene typy jako treba LongReport zaje jen asociuje jednodussi a vola jejich ser/deser()

class BaseCmd {
  virtual vector serializeCmd() const = 0;
  virtual void deserializeCmd(const vector) = 0;
}

class VersionCmd {
private:
  Version version;
public:
 vector serializeCmd() const override {
   Vector vector;
   version.serialize(vector);
  // ....
  return vector;
 }
  virtual void deserializeCmd(vector) override {
   version.deserialize(vector);
   // ....
 }
 version getVersion();
}
```

**Comment by nandra** [comment]
Napad vyzera ok len ja mam serializaciu + deserializaciu jednitnu cize ju nemusim pisat pre nove typy. Upravil som troska kod pre GetVersion command skus prosim pozriet do:

https://github.com/logimic/RdsGatewayRepM3/pull/new/mbe-wip

posledny komit. Su tam aj testy na to a je to podla toho ako je to definovane. serialize, deserialize + json serializacia. 

Myslim,ze by to takto mohlo byt. Ide hlavne o to aby sa to jednoducho pouzivalo, ak povies ze je to overkill prepisem to ;). Dik

**Comment by fmikulu** [comment]
Jaka je interni implementace ser/deser neni podstatne, pokud to funguje a je to udrzovatelne. Trochu me desi ty vnorene struktury, ale asi se tim prokousu, pokud bude treba. Testy mi nejdou prelozit pod Win a zatim nemam cas se tim zabyvat.

Napis mi prosim funkci priklad  (response data fake) jak by se to melo pouzivat do repM3.cpp. Co se tyka te JSON serializace, tak to budu muset stejne ohnout pro potreby API msg, hlavne ty casove udaje se budou prenaset jako stringy ISO: ""YYYY-MM-DDThh:mm:ss", nebo timestampy (sec since 1970), takze nepredpokladam, ze se to bude JSON serializovat 1:1. Spise se tedy pouzijou get/set funkce a sestavi se z toho potrebny JSON obj.

Pro inspiraci posilam co jsem dnes delal neco podobneho:
binarni protocol pres UART:

https://docs.google.com/spreadsheets/d/1OwIRtASPtDM2M2fG1k2inSpqVKU5QrCB/edit?usp=sharing&ouid=109434574881403105942&rtpof=true&sd=true

Co ma chodit po API:

https://drive.google.com/file/d/1WHeBDK8JKL6RKXvqB9xbz76_mgSm8_o8/view?usp=sharing

Jak jsem to implementoval:

[OffGridCoreMcu.zip](https://github.com/logimic/RdsGatewayRepM3/files/7818264/OffGridCoreMcu.zip)

**Comment by nandra** [comment]
Offgrid vyzera zaujimavo co som to zbezne pozrel. Uz zacinam chapat ako si to myslel.
Na pouzitie mam uz pridklad v teste vid: https://github.com/logimic/RdsGatewayRepM3/blob/e8f5b231ccdfa1fc068f35f07df744a9d4b9ab97/RepM3-test/main.cpp#L242

je tam serializace (ziadne data) a potom deserializacia prijatej odpovede a porovnanie hodnot. Od pondelka som v praci ak mozme si dat mozno kratky call. DIk

**Comment by fmikulu** [comment]
vyreseno
